# Generated by Django 5.1.6 on 2025-03-19 06:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("iot", "0002_alter_iotdevice_options_alter_iotdevice_estado"),
    ]

    operations = [
        migrations.RenameField(
            model_name="iotdevice",
            old_name="caracteristicas",
            new_name="characteristics",
        ),
        migrations.RenameField(
            model_name="iotdevice",
            old_name="tipo_dispositivo",
            new_name="device_type",
        ),
        migrations.RenameField(
            model_name="iotdevice",
            old_name="lote",
            new_name="id_lot",
        ),
        migrations.RenameField(
            model_name="iotdevice",
            old_name="predio",
            new_name="id_plot",
        ),
        migrations.RenameField(
            model_name="iotdevice",
            old_name="nombre",
            new_name="name",
        ),
        migrations.RemoveField(
            model_name="iotdevice",
            name="estado",
        ),
        migrations.AddField(
            model_name="iotdevice",
            name="is_active",
            field=models.BooleanField(
                db_index=True,
                default=True,
                help_text="Indica si el dispositivo esta habilitado",
                verbose_name="estado dispositivo",
            ),
        ),
    ]
