# Generated by Django 5.1.6 on 2025-03-19 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0004_alter_iotdevice_characteristics'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='iotdevice',
            options={'verbose_name': 'Dispositivo IoT', 'verbose_name_plural': 'Dispositivos IoT'},
        ),
        migrations.AddField(
            model_name='iotdevice',
            name='device_id',
            field=models.CharField(default=0, max_length=9, unique=True, verbose_name='ID del Dispositivo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='iotdevice',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Indica si el dispositivo está habilitado', verbose_name='estado dispositivo'),
        ),
    ]
