# Generated by Django 5.1.6 on 2025-04-01 03:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0008_iotdevice_owner_name'),
        ('plots_lots', '0007_alter_plot_plot_extension'),
    ]

    operations = [
        migrations.CreateModel(
            name='Valve',
            fields=[
                ('id_valve', models.CharField(editable=False, max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='Nombre de la válvula')),
                ('is_active', models.BooleanField(default=True, verbose_name='¿Está activa?')),
                ('actual_flow', models.FloatField(help_text='Caudal actual en metros cúbicos por segundo (m³/s)', verbose_name='Caudal actual')),
                ('id_lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valves', to='plots_lots.lot', verbose_name='Lote')),
                ('id_plot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valves', to='plots_lots.plot', verbose_name='Predio')),
                ('valve_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='valves', to='iot.devicetype', verbose_name='Tipo de válvula')),
            ],
            options={
                'verbose_name': 'Válvula',
                'verbose_name_plural': 'Válvulas',
                'ordering': ['id_valve'],
            },
        ),
    ]
