# Generated by Django 5.1.6 on 2025-04-02 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0008_iotdevice_owner_name'),
        ('plots_lots', '0007_alter_plot_plot_extension'),
    ]

    operations = [
        migrations.AddField(
            model_name='iotdevice',
            name='actual_flow',
            field=models.FloatField(blank=True, help_text='Caudal actual en litros por segundo (L/s)', null=True, verbose_name='Caudal actual (L/s)'),
        ),
        migrations.AddConstraint(
            model_name='iotdevice',
            constraint=models.UniqueConstraint(condition=models.Q(('device_type_id', '03')), fields=('device_type',), name='unique_valve_48'),
        ),
        migrations.AddConstraint(
            model_name='iotdevice',
            constraint=models.UniqueConstraint(condition=models.Q(('device_type_id', '14'), ('id_lot__isnull', True)), fields=('device_type', 'id_plot'), name='unique_valve_4_plot'),
        ),
        migrations.AddConstraint(
            model_name='iotdevice',
            constraint=models.UniqueConstraint(condition=models.Q(('device_type_id', '14'), ('id_plot__isnull', True)), fields=('device_type', 'id_lot'), name='unique_valve_4_lot'),
        ),
    ]