ärce# Generated by Django 5.1.6 on 2025-04-03 13:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0008_iotdevice_owner_name'),
        ('plots_lots', '0007_alter_plot_plot_extension'),
    ]

    operations = [
        migrations.AddField(
            model_name='iotdevice',
            name='actual_flow',
            field=models.FloatField(blank=True, help_text='Caudal actual en litros por segundo (L/s)', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(180)], verbose_name='Caudal actual (L/s)'),
        ),
        migrations.AddConstraint(
            model_name='iotdevice',
            constraint=models.UniqueConstraint(condition=models.Q(('device_type_id', '03')), fields=('device_type',), name='unique_valve_48'),
        ),
    ]
