# Generated by Django 5.1.6 on 2025-04-01 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0009_valve'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='valve',
            name='name',
        ),
    ]
