# Generated by Django 5.1.6 on 2025-04-03 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0009_iotdevice_actual_flow_iotdevice_unique_valve_48'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='iotdevice',
            name='unique_valve_48',
        ),
    ]
