# Generated by Django 5.1.6 on 2025-04-01 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0010_remove_valve_name'),
        ('plots_lots', '0007_alter_plot_plot_extension'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValveType',
            fields=[
                ('type_code', models.CharField(choices=[('BT', 'Bocatoma'), ('PR', 'Predio'), ('LT', 'Lote')], max_length=2, primary_key=True, serialize=False)),
                ('diameter', models.IntegerField()),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='valve',
            name='id_lot',
        ),
        migrations.RemoveField(
            model_name='valve',
            name='id_plot',
        ),
        migrations.AddField(
            model_name='valve',
            name='lot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='valves', to='plots_lots.lot', verbose_name='Lote'),
        ),
        migrations.AddField(
            model_name='valve',
            name='plot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='valves', to='plots_lots.plot', verbose_name='Predio'),
        ),
        migrations.AlterField(
            model_name='valve',
            name='valve_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='valves', to='iot.valvetype', verbose_name='Tipo de válvula'),
        ),
        migrations.AddConstraint(
            model_name='valve',
            constraint=models.UniqueConstraint(condition=models.Q(('valve_type', 'BT')), fields=('valve_type',), name='unique_bocatoma_valve'),
        ),
        migrations.AddConstraint(
            model_name='valve',
            constraint=models.UniqueConstraint(condition=models.Q(('valve_type', 'PR')), fields=('plot', 'valve_type'), name='unique_plot_valve'),
        ),
    ]
