# Generated by Django 5.1.6 on 2025-04-03 04:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0010_remove_iotdevice_unique_valve_4_plot_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iotdevice',
            name='actual_flow',
            field=models.FloatField(blank=True, help_text='Caudal actual en litros por segundo (L/s)', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(180)], verbose_name='Caudal actual (L/s)'),
        ),
    ]
