# Generated by Django 5.1.6 on 2025-04-23 14:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0011_alter_devicetype_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='iotdevice',
            name='registration_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de registro'),
        ),
    ]
