# Generated by Django 5.1.6 on 2025-04-01 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0011_valvetype_remove_valve_id_lot_remove_valve_id_plot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='iotdevice',
            name='actual_flow',
            field=models.FloatField(blank=True, help_text='Caudal actual en litros por segundo (L/s)', null=True, verbose_name='Caudal actual (L/s)'),
        ),
        migrations.AddConstraint(
            model_name='iotdevice',
            constraint=models.UniqueConstraint(condition=models.Q(('device_type_id', '03')), fields=('device_type',), name='unique_valve_48'),
        ),
        migrations.AddConstraint(
            model_name='iotdevice',
            constraint=models.UniqueConstraint(condition=models.Q(('device_type_id', '14'), ('id_lot__isnull', True)), fields=('device_type', 'id_plot'), name='unique_valve_4_plot'),
        ),
        migrations.AddConstraint(
            model_name='iotdevice',
            constraint=models.UniqueConstraint(condition=models.Q(('device_type_id', '14')), fields=('device_type', 'id_lot'), name='unique_valve_4_lot'),
        ),
        migrations.DeleteModel(
            name='Valve',
        ),
        migrations.DeleteModel(
            name='ValveType',
        ),
    ]
