# Generated by Django 5.1.6 on 2025-04-01 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0012_auto_20250401_1348'),
        ('plots_lots', '0007_alter_plot_plot_extension'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='iotdevice',
            name='unique_valve_4_plot',
        ),
        migrations.RemoveConstraint(
            model_name='iotdevice',
            name='unique_valve_4_lot',
        ),
        migrations.AddConstraint(
            model_name='iotdevice',
            constraint=models.UniqueConstraint(condition=models.Q(('device_type_id', '14'), ('id_lot__isnull', True)), fields=('id_plot', 'device_type'), name='unique_valve_4_plot'),
        ),
        migrations.AddConstraint(
            model_name='iotdevice',
            constraint=models.UniqueConstraint(condition=models.Q(('device_type_id', '14')), fields=('id_lot', 'device_type'), name='unique_valve_4_lot'),
        ),
    ]
