# Generated by Django 5.1.6 on 2025-04-23 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0012_iotdevice_registration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iotdevice',
            name='registration_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro'),
        ),
    ]
