# Generated by Django 5.1.6 on 2025-05-26 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0013_alter_iotdevice_registration_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='iotdevice',
            options={'permissions': [('change_bocatoma_flow', 'Puede cambiar caudal de válvula bocatoma'), ('change_all_lots_flow', 'Puede cambiar caudal de todas las válvulas de lotes')], 'verbose_name': 'Dispositivo IoT', 'verbose_name_plural': 'Dispositivos IoT'},
        ),
    ]
