# Generated by Django 5.1.6 on 2025-04-01 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0013_remove_iotdevice_unique_valve_4_plot_and_more'),
        ('plots_lots', '0007_alter_plot_plot_extension'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='iotdevice',
            name='unique_valve_4_plot',
        ),
        migrations.RemoveConstraint(
            model_name='iotdevice',
            name='unique_valve_4_lot',
        ),
        migrations.AddConstraint(
            model_name='iotdevice',
            constraint=models.UniqueConstraint(condition=models.Q(('device_type_id', '14')), fields=('device_type', 'id_lot'), name='unique_valve_4_lot'),
        ),
    ]
