# Generated by Django 5.1.6 on 2025-05-29 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0014_alter_iotdevice_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='iotdevice',
            options={'permissions': [('change_bocatoma_flow', 'Puede cambiar caudal de válvula bocatoma'), ('change_all_lots_flow', 'Puede cambiar caudal de todas las válvulas de lotes'), ('can_see_iot_totals', 'Puede ver los totalizados de IoT')], 'verbose_name': 'Dispositivo IoT', 'verbose_name_plural': 'Dispositivos IoT'},
        ),
    ]
