# Generated by Django 5.1.6 on 2025-04-01 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0015_remove_iotdevice_unique_valve_4_lot_and_more'),
        ('plots_lots', '0007_alter_plot_plot_extension'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='iotdevice',
            name='unique_valve_48',
        ),
        migrations.AddConstraint(
            model_name='iotdevice',
            constraint=models.UniqueConstraint(condition=models.Q(('device_type_id', '3')), fields=('device_type',), name='unique_valve_48'),
        ),
    ]
