# Generated by Django 5.1.6 on 2025-04-22 09:45

from django.db import migrations
def actualizar_permisos(apps, schema_editor):
    Permission = apps.get_model("auth", "Permission")
    ContentType = apps.get_model("contenttypes", "ContentType")

    # Obtener el ContentType existente
    content_type, _ = ContentType.objects.get_or_create(model="aquasmart_permission", app_label="AquaSmart")

    # 1️⃣ Eliminar permisos antiguos de AquaSmart
    Permission.objects.filter(content_type=content_type).delete()

    # 2️⃣ Agregar los nuevos permisos
    nuevos_permisos = [
       ("ver_pre_registros","	Permite visualizar los pre-registros"),
        ("aceptar_pre_registros","	Permite aceptar los pre-registros"),
        ("rechazar_pre_registros","	Permite rechazar los pre-registros"),
        ("asignar_permisos"," Permite asignar permisos a los usuarios"),
        ("ver_permisos_asignados","	Permite visualizar los permisos asignados"),
        ("quitar_permisos_asignados","	Permite revocar permisos asignados"),
        ("ver_roles_asignados","	Permite visualizar los roles asignados"),
        ("asignar_roles_asignados","	Permite asignar roles a los usuarios"),
        ("quitar_roles_asignados","	Permite quitar roles asignados"),
        ("ver_datos_personales","	Permite visualizar datos personales del usuario"),
        ("actualizar_datos_personales","	Permite actualizar datos personales del usuario"),
        ("eliminar_datos_personales","	Permite eliminar datos personales del usuario"),
        ("agregar_datos_personales","	Permite agregar datos personales del usuario"),
        ("visualizar_usuarios_distrito","	Permite visualizar todos los usuarios del distrito"),
        ("ver_info_usuarios_distrito","	Permite ver la información detallada de los usuarios"),
        ("actualizar_info_usuarios_distrito","	Permite actualizar la información de los usuarios"),
        ("eliminar_info_usuarios_distrito","	Permite eliminar información de los usuarios"),
        ("agregar_info_usuarios_distrito","	Permite agregar información de los usuarios"),
        ("ver_predios","	Permite visualizar los predios registrados"),
        ("registrar_info_predios","	Permite registrar información de predios"),
        ("eliminar_info_predios","	Permite eliminar información de predios"),
        ("actualizar_info_predios","	Permite actualizar información de predios"),
        ("ver_tarifas_cobro","	Permite ver las tarifas de cobro"),
        ("ingresar_tarifas_cobro","	Permite ingresar nuevas tarifas de cobro"),
        ("modificar_tarifas_cobro","	Permite modificar tarifas de cobro existentes"),
        ("eliminar_tarifas_cobro","	Permite eliminar tarifas de cobro"),
        ("ver_historial_consumo_general_distrito","	Permite ver el historial de consumo general del distrito"),
        ("ver_historial_consumo_predios","	Permite ver el historial de consumo de los predios"),
        ("ver_historial_consumo_lotes","	Permite ver el historial de consumo de los lotes"),
        ("ver_historial_consumo_predios_individuales","	Permite ver el historial de consumo de un predio específico"),
        ("ver_historial_consumo_lotes_individuales","	Permite ver el historial de consumo de un lote específico"),
        ("generar_facturas_cobro","	Permite generar facturas de cobro"),
        ("enviar_facturas_cobro","	Permite enviar facturas de cobro a los usuarios"),
        ("descargar_facturas_distrito_pdf","	Permite descargar facturas del distrito en formato PDF"),
        ("ver_historial_facturas_usuarios","	Permite ver el historial de facturación de los usuarios"),
        ("pagar_online_pse","	Permite realizar pagos en línea mediante PSE"),
        ("ver_facturas_pagadas","	Permite ver las facturas pagadas"),
        ("ver_facturas_vencidas","	Permite ver las facturas vencidas"),
        ("generar_reportes_fallos","	Permite generar reportes de fallos y daños"),
        ("ver_reportes_fallos","	Permite visualizar reportes de fallos y daños"),
        ("eliminar_reportes_fallos","	Permite eliminar reportes de fallos y daños"),
        ("modificar_reportes_fallos","	Permite modificar reportes de fallos y daños"),
        ("ver_informe_mantenimiento","	Permite ver informes de mantenimiento"),
        ("crear_informe_mantenimiento","	Permite crear informes de mantenimiento"),
        ("eliminar_informe_mantenimiento","	Permite eliminar informes de mantenimiento"),
        ("modificar_informe_mantenimiento","	Permite modificar informes de mantenimiento"),
        ("descargar_inventario_iot","	Permite descargar el inventario de dispositivos IoT"),
        ("generar_prediccion_distrito","	permite generar predicciones de consumo del distrito"),
        ("ver_predicciones_distrito","	permite ver las predicciones de consumo del distrito"),
        ("eliminar_prediccion_distrito","	Permite eliminar las predicciones de consumo del distrito"),
        ("ver_lotes","	 permite visualizar los lotes del distrito"),
        ("actualizar_info_lotes","	permite actualizar la informacion de los lotes"),
        ("inhabilitar_predios","	permite inhabilitar predios"),
        ("inhabilitar_lotes","	permite inhabilitar lotes"),
        ("ver_disp_iot","	permite ver dispositivos iot"),
        ("registrar_disp_iot","	permite registrar dispositivos iot"),
        ("inhabilitar_disp_iot","	permite inhabilitar dispositivos iot"),
        ("habilitar_disp_iot","	permite habilitar dispositivos iot"),
        ("registrar_info_lotes","	Permite registrar informacion de lotes"),
        ("ver_mi_historial_facturas","	Permite al usuario ver su propio historial de facturas"),
        ("solicitar_cambio_caudal","	Permite realizar solicitudes de cambio de caudal"),
        ("ver_predicciones_predios","	permite ver las predicciones de consumo del distrito"),
        ("generar_predicciones_predios","	permite generar predicciones de consumo de todos los predios"),
        ("eliminar_predicciones_predios","	permite eliminar predicciones de consumo de todos los predios"),
        ("eliminar_predicciones_lotes","	permite eliminar predicciones de consumo de todos los lotes"),
        ("generar_predicciones_lotes","	permite generar predicciones de consumo de todos los lotes"),
        ("ver_predicciones_lotes","	permite ver predicciones de consumo de todos los lotes"),
        ("eliminar_prediccion_consumo_mi_predio","	permite eliminar predicciones de consumo del predio correspondiente al usuario"),
        ("generar_prediccion_consumo_mi_predio","	permite generar predicciones de consumo del predio correspondiente al usuario"),
        ("ver_prediccion_consumo_mi_predio","	permite ver predicciones de consumo del predio correspondiente al usuario"),
        ("eliminar_prediccion_consumo_mi_lote","	permite eliminar predicciones de consumo del lote correspondiente al usuario"),
        ("generar_prediccion_consumo_mi_lote","	permite generar predicciones de consumo del lote correspondiente al usuario"),
        ("ver_prediccion_consumo_mi_lote","	permite ver predicciones de consumo del lote correspondiente al usuario"),
    ]

    for codename, descripcion in nuevos_permisos:
        Permission.objects.get_or_create(
            codename=codename,
            name=descripcion,
            content_type=content_type
        )

class Migration(migrations.Migration):

    dependencies = [
        ('AquaSmart', '0001_add_custom_permissions'),
    ]

    operations = [
        migrations.RunPython(actualizar_permisos),
    ]
