# Generated by Django 5.1.6 on 2025-04-07 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'Empresa', 'verbose_name_plural': 'Datos de la empresa'},
        ),
        migrations.AlterModelOptions(
            name='consumptionrate',
            options={'verbose_name': 'Tarifa de Consumo', 'verbose_name_plural': 'Tarifas de Consumo'},
        ),
        migrations.AlterModelOptions(
            name='taxrate',
            options={'verbose_name': 'Tarifa de Impuesto', 'verbose_name_plural': 'Tarifas de Impuesto'},
        ),
        migrations.AlterField(
            model_name='company',
            name='nit',
            field=models.CharField(max_length=11, unique=True),
        ),
        migrations.AlterField(
            model_name='consumptionrate',
            name='fixed_rate_cents',
            field=models.PositiveIntegerField(help_text='Tarifa fija por consumo en centavos', verbose_name='Tarifa fija'),
        ),
        migrations.AlterField(
            model_name='consumptionrate',
            name='volumetric_rate_cents',
            field=models.PositiveIntegerField(help_text='Tarifa por unidad de volumen (m³) en centavos', verbose_name='Tarifa volumétrica'),
        ),
    ]
