# Generated by Django 5.1.6 on 2025-04-15 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_rename_id_empresa_company_id_company_and_more'),
        ('plots_lots', '0008_croptype_lot_crop_name_alter_lot_crop_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='FixedConsumptionRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Código de la tarifa fija (e.j., TFA, TFP)', max_length=3, unique=True, verbose_name='Código de la tarifa fija')),
                ('fixed_rate_cents', models.PositiveIntegerField(help_text='Tarifa fija por consumo en centavos', verbose_name='Tarifa fija')),
                ('crop_type', models.OneToOneField(help_text='Tipo de cultivo (e.j., Agricultura, Psicultura)', on_delete=django.db.models.deletion.CASCADE, to='plots_lots.croptype', verbose_name='Tipo de cultivo')),
            ],
            options={
                'verbose_name': 'Tarifa Fija de Consumo',
                'verbose_name_plural': 'Tarifas Fijas de Consumo',
            },
        ),
        migrations.CreateModel(
            name='VolumetricConsumptionRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Código de la tarifa volumétrica (e.j., TVA, TVP)', max_length=3, unique=True, verbose_name='Código de la tarifa volumétrica')),
                ('volumetric_rate_cents', models.PositiveIntegerField(help_text='Tarifa por unidad de volumen (m³) en centavos', verbose_name='Tarifa volumétrica')),
                ('crop_type', models.OneToOneField(help_text='Tipo de cultivo (e.j., Agricultura, Psicultura)', on_delete=django.db.models.deletion.CASCADE, to='plots_lots.croptype', verbose_name='Tipo de cultivo')),
            ],
            options={
                'verbose_name': 'Tarifa Volumétrica de Consumo',
                'verbose_name_plural': 'Tarifas Volumétricas de Consumo',
            },
        ),
        migrations.DeleteModel(
            name='ConsumptionRate',
        ),
    ]
