# Generated by Django 5.1.6 on 2025-05-25 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0008_invoiceapi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='status',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('pagada', 'Pagada'), ('vencida', 'Vencida')], default='pendiente', help_text='Estado actual de la factura', max_length=10, verbose_name='Estado de la factura'),
        ),
    ]
