# Generated by Django 5.1.6 on 2025-05-29 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0009_alter_bill_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bill',
            options={'permissions': [('can_see_invoice_totals', 'Puede ver los totalizados de las facturas')], 'verbose_name': 'Factura', 'verbose_name_plural': 'Facturas'},
        ),
    ]
