# Generated by Django 5.1.6 on 2025-04-04 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plots_lots', '0007_alter_plot_plot_extension'),
    ]

    operations = [
        migrations.CreateModel(
            name='CropType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Tipo de cultivo')),
            ],
            options={
                'verbose_name': 'Tipo de cultivo',
                'verbose_name_plural': 'Tipos de cultivo',
            },
        ),
        migrations.AddField(
            model_name='lot',
            name='crop_name',
            field=models.CharField(default='Sin nombre', max_length=20, verbose_name='Nombre del cultivo'),
        ),
        migrations.AlterField(
            model_name='lot',
            name='crop_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plots_lots.croptype', verbose_name='Tipo de cultivo'),
        ),
    ]
