# Generated by Django 5.1.6 on 2025-03-19 21:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("plots_lots", "0007_merge_20250317_1936"),
        ("plots_lots", "0007_merge_20250317_1938"),
    ]

    operations = []
