# Generated by Django 5.1.6 on 2025-03-21 14:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("plots_lots", "0007_alter_plot_plot_extension"),
        ("plots_lots", "0009_alter_plot_plot_extension"),
    ]

    operations = []
