# Generated by Django 5.1.6 on 2025-03-20 03:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("plots_lots", "0008_merge_20250319_1655"),
        ("plots_lots", "0009_alter_plot_plot_extension"),
    ]

    operations = []
