# Generated by Django 5.1.6 on 2025-03-21 18:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("plots_lots", "0010_merge_20250319_2201"),
        ("plots_lots", "0010_merge_20250321_0919"),
    ]

    operations = []
