# Generated by Django 5.1.6 on 2025-04-07 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plots_lots', '0008_croptype_lot_crop_name_alter_lot_crop_type'),
        ('plots_lots', '0011_merge_20250321_1304'),
    ]

    operations = [
    ]
