# Generated by Django 5.2 on 2025-05-24 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device', models.CharField(max_length=20)),
                ('timestamp', models.DateTimeField()),
                ('consumo_parcial_L', models.FloatField()),
                ('consumo_dia_L', models.FloatField()),
                ('consumo_mes_L', models.FloatField()),
                ('contador_unidades', models.PositiveIntegerField()),
            ],
        ),
    ]
