# Generated by Django 5.2 on 2025-05-24 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esp', '0001_initial'),
        ('iot', '0013_alter_iotdevice_registration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumo',
            name='device',
            field=models.ForeignKey(db_column='device', on_delete=django.db.models.deletion.CASCADE, to='iot.iotdevice', verbose_name='Dispositivo IoT'),
        ),
    ]
