# Generated by Django 5.1.6 on 2025-05-26 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esp', '0002_alter_consumo_device'),
        ('iot', '0014_alter_iotdevice_options'),
        ('plots_lots', '0008_croptype_lot_crop_name_alter_lot_crop_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnviosContador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contador', models.PositiveIntegerField(default=0)),
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='iot.iotdevice')),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plots_lots.lot')),
            ],
        ),
    ]
