# Generated by Django 5.1.6 on 2025-04-30 19:04

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacion',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ACEPTADA', 'Aceptada'), ('RECHAZADA', 'Rechazada'), ('COMPLETADA', 'Completada')], default='PENDIENTE', max_length=50),
        ),
        migrations.AddField(
            model_name='reporte',
            name='tipo',
            field=models.CharField(choices=[('MANTENIMIENTO', 'Mantenimiento'), ('REPARACION', 'Reparación'), ('INCIDENTE', 'Incidente')], default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='asignacion',
            name='instrucciones',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='asignacion',
            name='reporte',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='reportes.reporte'),
        ),
        migrations.AlterField(
            model_name='asignacion',
            name='tecnico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ASIGNADO', 'Asignado'), ('EN_PROCESO', 'En proceso'), ('COMPLETADO', 'Completado')], default='PENDIENTE', max_length=50),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='titulo',
            field=models.CharField(max_length=200),
        ),
    ]
