# Generated by Django 5.1.6 on 2025-04-30 19:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0002_asignacion_estado_reporte_tipo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporte',
            name='tipo',
            field=models.CharField(choices=[('MANTENIMIENTO', 'Mantenimiento'), ('REPARACION', 'Reparación'), ('INCIDENTE', 'Incidente'), ('CAUDAL', 'Solicitud de caudal'), ('APLICATIVO', 'Fallo en aplicativo')], default='MANTENIMIENTO', max_length=50),
        ),
        migrations.CreateModel(
            name='InformeMantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_solucion', models.TextField()),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('COMPLETADO', 'Completado')], default='PENDIENTE', max_length=20)),
                ('asignacion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='informe', to='reportes.asignacion')),
                ('reporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='informes', to='reportes.reporte')),
                ('tecnico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
