# Generated by Django 5.1.6 on 2025-04-30 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0003_alter_reporte_tipo_informemantenimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporte',
            name='tipo',
            field=models.CharField(choices=[('MANTENIMIENTO', 'Mantenimiento'), ('REPARACION', 'Reparación'), ('INCIDENTE', 'Incidente'), ('CAUDAL', 'Solicitud de caudal'), ('APLICATIO', 'Fallo en aplicativo')], default='MANTENIMIENTO', max_length=50),
        ),
    ]
