# Generated by Django 5.1.6 on 2025-04-30 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0004_alter_reporte_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reporte',
            name='fecha_limite',
        ),
        migrations.RemoveField(
            model_name='reporte',
            name='responsable',
        ),
        migrations.AlterField(
            model_name='reporte',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ASIGNADO', 'Asignado'), ('EN_PROCESO', 'En proceso'), ('COMPLETADO', 'Completado')], default='PENDIENTE', editable=False, max_length=50),
        ),
    ]
