# Generated by Django 5.1.6 on 2025-04-30 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0005_remove_reporte_fecha_limite_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='informemantenimiento',
            name='aprobado',
            field=models.BooleanField(default=False, verbose_name='Aprobado por administrador'),
        ),
    ]
