# Generated by Django 5.1.6 on 2025-05-01 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0006_informemantenimiento_aprobado'),
    ]

    operations = [
        migrations.AddField(
            model_name='informemantenimiento',
            name='image_base64',
            field=models.TextField(blank=True, null=True, verbose_name='Imagen del informe'),
        ),
    ]
