# Generated by Django 5.1.6 on 2025-04-30 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailnotification',
            name='metadata',
            field=models.JSONField(default=dict),
        ),
    ]
