# Generated by Django 5.1.6 on 2025-04-25 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0003_flowactivationrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flowchangerequest',
            name='device',
        ),
    ]
