# Generated by Django 5.1.6 on 2025-04-25 23:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0004_remove_flowchangerequest_device'),
        ('plots_lots', '0008_croptype_lot_crop_name_alter_lot_crop_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WaterSupplyFailureReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada')], default='pendiente', help_text='Estado actual de la solicitud', max_length=10, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora en que se creó la solicitud', verbose_name='Fecha solicitud')),
                ('reviewed_at', models.DateTimeField(blank=True, help_text='Fecha y hora en que la solicitud fue revisada (aprobada o rechazada)', null=True, verbose_name='Fecha revisión')),
                ('observations', models.CharField(help_text='Detalle del fallo reportado (hasta 200 caracteres)', max_length=200, verbose_name='Observaciones')),
                ('lot', models.ForeignKey(blank=True, help_text='Lote al que se le solicita el cambio de caudal', null=True, on_delete=django.db.models.deletion.CASCADE, to='plots_lots.lot', verbose_name='Lote')),
                ('plot', models.ForeignKey(blank=True, help_text='Predio de la válvula principal (si es válvula principal de predio)', null=True, on_delete=django.db.models.deletion.CASCADE, to='plots_lots.plot', verbose_name='Predio')),
                ('user', models.ForeignKey(help_text='Usuario que realiza la solicitud de cambio de caudal', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Solicitante')),
            ],
            options={
                'verbose_name': 'Reporte de fallo de suministro de agua',
                'verbose_name_plural': 'Reportes de fallos de suministro de agua',
                'abstract': False,
            },
        ),
    ]
