# Generated by Django 5.1.6 on 2025-04-26 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0005_watersupplyfailurereport'),
        ('plots_lots', '0008_croptype_lot_crop_name_alter_lot_crop_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watersupplyfailurereport',
            name='lot',
            field=models.ForeignKey(blank=True, help_text='Lote afectado (opcional)', null=True, on_delete=django.db.models.deletion.CASCADE, to='plots_lots.lot', verbose_name='Lote'),
        ),
        migrations.AlterField(
            model_name='watersupplyfailurereport',
            name='plot',
            field=models.ForeignKey(default=0, help_text='Predio donde ocurre el fallo.', on_delete=django.db.models.deletion.CASCADE, to='plots_lots.plot', verbose_name='Predio'),
            preserve_default=False,
        ),
    ]
