# Generated by Django 5.1.6 on 2025-04-28 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0006_alter_watersupplyfailurereport_lot_and_more'),
        ('plots_lots', '0012_merge_20250407_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watersupplyfailurereport',
            name='lot',
            field=models.ForeignKey(blank=True, help_text='Lote al que se le solicita el cambio de caudal', null=True, on_delete=django.db.models.deletion.CASCADE, to='plots_lots.lot', verbose_name='Lote'),
        ),
        migrations.AlterField(
            model_name='watersupplyfailurereport',
            name='plot',
            field=models.ForeignKey(blank=True, help_text='Predio de la válvula principal (si es válvula principal de predio)', null=True, on_delete=django.db.models.deletion.CASCADE, to='plots_lots.plot', verbose_name='Predio'),
        ),
    ]
