# Generated by Django 5.1.6 on 2025-04-28 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0008_applicationfailurereport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationfailurereport',
            name='status',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('resuelto', 'Resuelto')], default='pendiente', max_length=10),
        ),
    ]
