# Generated by Django 5.1.6 on 2025-05-08 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0010_remove_flowactivationrequest_lot_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flowrequest',
            name='id',
            field=models.IntegerField(help_text='Identificador único de la solicitud', primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
