# Generated by Django 5.1.6 on 2025-05-08 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0011_alter_flowrequest_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='failurereport',
            options={'verbose_name': 'Reporte de Fallo', 'verbose_name_plural': 'Reportes de Fallo'},
        ),
    ]
