# Generated by Django 5.1.6 on 2025-05-09 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0012_alter_failurereport_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='observations',
            field=models.TextField(blank=True, help_text='Observaciones adicionales sobre la asignación', null=True, verbose_name='Observaciones'),
        ),
        migrations.AddField(
            model_name='maintenancereport',
            name='actions_taken',
            field=models.TextField(blank=True, help_text='Acciones tomadas para resolver los problemas', null=True, verbose_name='Acciones realizadas'),
        ),
        migrations.AddField(
            model_name='maintenancereport',
            name='findings',
            field=models.TextField(blank=True, help_text='Problemas encontrados durante la intervención', null=True, verbose_name='Hallazgos'),
        ),
        migrations.AddField(
            model_name='maintenancereport',
            name='recommendations',
            field=models.TextField(blank=True, help_text='Recomendaciones para futuras intervenciones', null=True, verbose_name='Recomendaciones'),
        ),
        migrations.AlterField(
            model_name='maintenancereport',
            name='description',
            field=models.TextField(blank=True, help_text='Descripción detallada de la intervención realizada', null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='maintenancereport',
            name='images',
            field=models.TextField(blank=True, help_text='Imágenes de la intervención realizada (en base64 o URLs)', null=True, verbose_name='Imágenes'),
        ),
    ]
