# Generated by Django 5.1.6 on 2025-05-11 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0012_alter_failurereport_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='failurereport',
            name='failure_type',
            field=models.CharField(choices=[('Fallo en el Suministro del Agua', 'Fallo en el Suministro del Agua'), ('Fallo en el Aplicativo', 'Fallo en el Aplicativo')], help_text='Tipo de reporte (suministro de agua o aplicativo)', max_length=50, verbose_name='Tipo de reporte'),
        ),
        migrations.AlterField(
            model_name='flowrequest',
            name='flow_request_type',
            field=models.CharField(choices=[('Cambio de Caudal', 'Cambio de Caudal'), ('Cancelación Temporal de Caudal', 'Cancelación Temporal de Caudal'), ('Cancelación Definitiva de Caudal', 'Cancelación Definitiva de Caudal'), ('Activación de Caudal', 'Activación de Caudal')], help_text='Tipo de solicitud de caudal', max_length=80, verbose_name='Tipo de solicitud'),
        ),
    ]
