# Generated by Django 5.1.6 on 2025-05-09 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0013_assignment_observations_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flowrequest',
            name='flow_request_type',
            field=models.CharField(choices=[('Cambio de Caudal', 'Cambio de Caudal'), ('Cancelación Temporal de Caudal', 'Cancelación Temporal de Caudal'), ('Cancelación Definitiva de Caudal', 'Cancelación Definitiva de Caudal'), ('Activación de Caudal', 'Activación de Caudal')], help_text='Tipo de solicitud de caudal', max_length=80, verbose_name='Tipo de solicitud'),
        ),
    ]
