# Generated by Django 5.1.6 on 2025-05-15 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0013_alter_failurereport_failure_type_and_more'),
        ('communication', '0014_alter_flowrequest_flow_request_type'),
    ]

    operations = [
    ]
