# Generated by Django 5.1.6 on 2025-05-15 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0015_merge_20250515_1138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='observations',
        ),
        migrations.RemoveField(
            model_name='maintenancereport',
            name='actions_taken',
        ),
        migrations.RemoveField(
            model_name='maintenancereport',
            name='findings',
        ),
        migrations.RemoveField(
            model_name='maintenancereport',
            name='recommendations',
        ),
        migrations.AlterField(
            model_name='maintenancereport',
            name='description',
            field=models.TextField(blank=True, help_text='Descripción de la intervención realizada', null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='maintenancereport',
            name='images',
            field=models.TextField(blank=True, help_text='Imágenes de la intervención realizada', null=True, verbose_name='Imágenes'),
        ),
    ]
