# Generated by Django 5.1.6 on 2025-05-16 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0016_remove_assignment_observations_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assignment',
            options={'permissions': [('can_be_assigned', 'Puede puede ser asignado')], 'verbose_name': 'Asignación de solicitud/reporte', 'verbose_name_plural': 'Asignaciones de solicitudes/reportes'},
        ),
    ]
