# Generated by Django 5.1.6 on 2025-05-16 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0017_alter_assignment_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assignment',
            options={'permissions': [('can_be_assigned', 'Puede puede ser asignado'), ('can_assign_user', 'Puede asignar un usuario')], 'verbose_name': 'Asignación de solicitud/reporte', 'verbose_name_plural': 'Asignaciones de solicitudes/reportes'},
        ),
    ]
