# Generated by Django 5.1.6 on 2025-05-25 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0019_alter_assignment_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assignment',
            options={'permissions': [('can_be_assigned', 'Puede puede ser asignado'), ('can_assign_user', 'Puede asignar un usuario'), ('Can_view_assignment', 'Puede ver asignaciones'), ('view_all_assignments', 'Puede ver todas las asignaciones'), ('can_manage_reports', 'Puede aprobar o re-asignar informes')], 'verbose_name': 'Asignación de solicitud/reporte', 'verbose_name_plural': 'Asignaciones de solicitudes/reportes'},
        ),
    ]
