# Generated by Django 5.1.6 on 2025-03-23 23:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("iot", "0008_iotdevice_owner_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="FlowMeasurement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "flow_rate",
                    models.FloatField(
                        help_text="Caudal medido en metros cúbicos por segundo (m³/s)"
                    ),
                ),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="flow_measurements",
                        to="iot.iotdevice",
                    ),
                ),
            ],
            options={
                "verbose_name": "Medición de Caudal",
                "verbose_name_plural": "Mediciones de Caudal",
                "ordering": ["-timestamp"],
            },
        ),
    ]
