# Generated by Django 5.1.6 on 2025-03-24 04:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("caudal", "0002_flowmeasurementplotslots"),
        ("plots_lots", "0007_alter_plot_plot_extension"),
    ]

    operations = [
        migrations.CreateModel(
            name="FlowInconsistency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "recorded_flow",
                    models.FloatField(
                        verbose_name="Caudal registrado en el predio (m³/s)"
                    ),
                ),
                (
                    "total_lots_flow",
                    models.FloatField(
                        verbose_name="Suma de caudales de los lotes (m³/s)"
                    ),
                ),
                (
                    "difference",
                    models.FloatField(verbose_name="Diferencia de caudales (m³/s)"),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de detección"
                    ),
                ),
                (
                    "plot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="flow_inconsistencies",
                        to="plots_lots.plot",
                        verbose_name="Predio",
                    ),
                ),
            ],
            options={
                "verbose_name": "Inconsistencia de caudal",
                "verbose_name_plural": "Inconsistencias de caudal",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="FlowMeasurementLote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("flow_rate", models.FloatField(verbose_name="Caudal (m³/s)")),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha y Hora"
                    ),
                ),
                (
                    "lot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="flow_measurements_lote",
                        to="plots_lots.lot",
                        verbose_name="Lote",
                    ),
                ),
            ],
            options={
                "verbose_name": "Medición de Caudal de Lote",
                "verbose_name_plural": "Mediciones de Caudal de Lotes",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="FlowMeasurementPredio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("flow_rate", models.FloatField(verbose_name="Caudal (m³/s)")),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha y Hora"
                    ),
                ),
                (
                    "plot",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="flow_measurement_predio",
                        to="plots_lots.plot",
                        verbose_name="Predio",
                    ),
                ),
            ],
            options={
                "verbose_name": "Medición de Caudal de Predio",
                "verbose_name_plural": "Mediciones de Caudal de Predios",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.DeleteModel(
            name="FlowMeasurementPlotsLots",
        ),
    ]
