# Generated by Django 5.1.6 on 2025-03-24 05:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("caudal", "0004_alter_flowmeasurementpredio_plot"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flowmeasurementlote",
            name="timestamp",
            field=models.DateTimeField(verbose_name="Fecha y Hora"),
        ),
        migrations.AlterField(
            model_name="flowmeasurementpredio",
            name="timestamp",
            field=models.DateTimeField(verbose_name="Fecha y Hora"),
        ),
    ]
