# Generated by Django 5.1.6 on 2025-03-24 06:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("caudal", "0005_alter_flowmeasurementlote_timestamp_and_more"),
        ("iot", "0008_iotdevice_owner_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="flowmeasurementlote",
            name="device",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="flow_measurements_lote",
                to="iot.iotdevice",
                verbose_name="Dispositivo IoT",
            ),
        ),
        migrations.AddField(
            model_name="flowmeasurementpredio",
            name="device",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="flow_measurements_predio",
                to="iot.iotdevice",
                verbose_name="Dispositivo IoT",
            ),
        ),
    ]
