# Generated by Django 5.1.6 on 2025-05-01 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caudal', '0007_alter_flowmeasurementlote_flow_rate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flowmeasurementlote',
            name='flow_rate',
            field=models.FloatField(verbose_name='Caudal (m³/s)'),
        ),
        migrations.DeleteModel(
            name='WaterConsumptionRecord',
        ),
    ]
