# Generated by Django 5.1.6 on 2025-05-15 01:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_bill'),
        ('caudal', '0008_alter_flowmeasurementlote_flow_rate_and_more'),
        ('iot', '0013_alter_iotdevice_registration_date'),
        ('plots_lots', '0008_croptype_lot_crop_name_alter_lot_crop_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flowmeasurementlote',
            name='flow_rate',
            field=models.FloatField(verbose_name='Caudal (L/s)'),
        ),
        migrations.CreateModel(
            name='WaterConsumptionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_reading', models.FloatField(help_text='Lectura anterior del medidor en metros cúbicos', verbose_name='Lectura anterior (m³)')),
                ('current_reading', models.FloatField(help_text='Lectura actual del medidor en metros cúbicos', verbose_name='Lectura actual (m³)')),
                ('start_date', models.DateTimeField(verbose_name='Fecha inicial del periodo')),
                ('end_date', models.DateTimeField(verbose_name='Fecha final del periodo')),
                ('period_consumption', models.FloatField(help_text='Consumo de agua durante el periodo actual', verbose_name='Consumo del periodo (m³)')),
                ('monthly_consumption', models.FloatField(help_text='Consumo total del mes calendario', verbose_name='Consumo mensual (m³)')),
                ('accumulated_consumption', models.FloatField(help_text='Consumo total acumulado desde la instalación', verbose_name='Consumo acumulado (m³)')),
                ('billed', models.BooleanField(default=False, help_text='Indica si este consumo ya ha sido facturado', verbose_name='Facturado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('bill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consumption_records', to='billing.bill', verbose_name='Factura asociada')),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='water_consumption_records', to='iot.iotdevice', verbose_name='Dispositivo IoT')),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='water_consumption_records', to='plots_lots.lot', verbose_name='Lote')),
            ],
            options={
                'verbose_name': 'Registro de Consumo de Agua',
                'verbose_name_plural': 'Registros de Consumo de Agua',
                'ordering': ['-end_date'],
            },
        ),
    ]
