# Generated by Django 5.1.6 on 2025-05-17 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClimateRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('tempmax', models.FloatField()),
                ('tempmin', models.FloatField()),
                ('precip', models.FloatField()),
                ('precipprob', models.FloatField()),
                ('precipcover', models.FloatField()),
                ('windgust', models.FloatField()),
                ('windspeed', models.FloatField()),
                ('pressure', models.FloatField()),
                ('cloudcover', models.FloatField()),
                ('solarradiation', models.FloatField()),
                ('sunrise', models.TimeField()),
                ('sunset', models.TimeField()),
                ('luminiscencia', models.FloatField()),
                ('final_date', models.DateTimeField()),
            ],
        ),
    ]
