# Generated by Django 5.1.6 on 2025-05-21 03:44

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ia', '0001_initial'),
        ('plots_lots', '0008_croptype_lot_crop_name_alter_lot_crop_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsuptionPredictionLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_time', models.CharField(choices=[('1', '1'), ('3', '3'), ('6', '6')], help_text='Tiempo a elegir', max_length=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)], verbose_name='Tiempo a elegir')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha de creacion de la prediccion', verbose_name='Fecha de creacion de la prediccion')),
                ('consumption_prediction', models.FloatField(help_text='Consumo predecido', verbose_name='Consumo predecido')),
                ('code_prediction', models.CharField(help_text='Codigo de las predicciones', max_length=20, verbose_name='Codigo para las predicciones')),
                ('final_date', models.DateTimeField()),
                ('lot', models.ForeignKey(help_text='id del lote', on_delete=django.db.models.deletion.CASCADE, to='plots_lots.lot', verbose_name='Id del lote')),
                ('user', models.ForeignKey(help_text='Documento usuario que hizo la peticion', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Documento usuario que hizo la peticion')),
            ],
        ),
    ]
