# Generated by Django 5.1.6 on 2025-05-22 15:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IA', '0003_consuptionpredictionlot_date_prediction_and_more'),
        ('plots_lots', '0008_croptype_lot_crop_name_alter_lot_crop_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='climaterecord',
            options={'verbose_name': 'Registro climático', 'verbose_name_plural': 'Registros climáticos'},
        ),
        migrations.AlterModelOptions(
            name='consuptionpredictionlot',
            options={'verbose_name': 'Predicción de consumo de lote', 'verbose_name_plural': 'Predicción de consumo de lotes'},
        ),
        migrations.AlterField(
            model_name='consuptionpredictionlot',
            name='code_prediction',
            field=models.CharField(help_text='Código de las predicciones', max_length=20, verbose_name='Código para las predicciones'),
        ),
        migrations.AlterField(
            model_name='consuptionpredictionlot',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Fecha de creacion de la predicción', verbose_name='Fecha de creación de la prediccion'),
        ),
        migrations.AlterField(
            model_name='consuptionpredictionlot',
            name='date_prediction',
            field=models.DateField(help_text='Meses de predicción', null=True, verbose_name='Meses de predicción'),
        ),
        migrations.AlterField(
            model_name='consuptionpredictionlot',
            name='lot',
            field=models.ForeignKey(help_text='Lote al que se le realiza la predicción', on_delete=django.db.models.deletion.CASCADE, to='plots_lots.lot', verbose_name='Lote'),
        ),
        migrations.AlterField(
            model_name='consuptionpredictionlot',
            name='period_time',
            field=models.CharField(choices=[('1', '1'), ('3', '3'), ('6', '6')], help_text='Periodo de tiempo (meses) a predecir', max_length=1, verbose_name='Periodo mensual de predicción'),
        ),
        migrations.AlterField(
            model_name='consuptionpredictionlot',
            name='user',
            field=models.ForeignKey(help_text='Usuario que solicita la predicción', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario solicitante'),
        ),
    ]
