# Generated by Django 5.1.6 on 2025-05-23 22:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IA', '0004_alter_climaterecord_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsuptionPredictionBocatoma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_time', models.CharField(choices=[('1', '1'), ('3', '3'), ('6', '6')], help_text='Periodo de tiempo (meses) a predecir', max_length=1, verbose_name='Periodo mensual de predicción')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha de creacion de la predicción', verbose_name='Fecha de creación de la prediccion')),
                ('date_prediction', models.DateField(help_text='Meses de predicción', null=True, verbose_name='Meses de predicción')),
                ('consumption_prediction', models.FloatField(help_text='Consumo predecido', verbose_name='Consumo predecido')),
                ('code_prediction', models.CharField(help_text='Código de las predicciones', max_length=20, verbose_name='Código para las predicciones')),
                ('final_date', models.DateTimeField()),
                ('user', models.ForeignKey(help_text='Usuario que solicita la predicción', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario solicitante')),
            ],
            options={
                'verbose_name': 'Predicción de consumo de lote',
                'verbose_name_plural': 'Predicción de consumo de lotes',
            },
        ),
    ]
