# Generated by Django 5.1.6 on 2025-05-24 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IA', '0005_consuptionpredictionbocatoma'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consuptionpredictionbocatoma',
            options={'verbose_name': 'Predicción de consumo de bocatoma', 'verbose_name_plural': 'Predicciones de consumo de bocatoma'},
        ),
    ]
