# Generated by Django 5.1.6 on 2025-05-28 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IA', '0006_alter_consuptionpredictionbocatoma_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consuptionpredictionbocatoma',
            options={'permissions': [('can_see_predictions_boacatoma', 'Puede ver predicciones de la bocatoma'), ('can_make_predictions_bocatoma', 'Puede hacer prediciones a la bocatoma')], 'verbose_name': 'Predicción de consumo de bocatoma', 'verbose_name_plural': 'Predicciones de consumo de bocatoma'},
        ),
    ]
