# Generated by Django 5.1.6 on 2025-02-12 00:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="otp",
            name="is_validated",
            field=models.BooleanField(default=False),
        ),
    ]
