# Generated by Django 5.1.6 on 2025-02-18 18:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_otp_is_validated"),
    ]

    operations = [
        migrations.AddField(
            model_name="otp",
            name="is_login",
            field=models.BooleanField(default=False),
        ),
    ]
