# Generated by Django 5.1.6 on 2025-02-18 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_otp_is_login'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='isRegistered',
            new_name='is_registered',
        ),
    ]
