# Generated by Django 5.1.6 on 2025-03-04 11:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_alter_customuser_options_alter_loginhistory_options_and_more"),
        ("users", "0006_alter_customuser_document_type_and_more"),
    ]

    operations = []
