# Generated by Django 5.1.6 on 2025-03-07 13:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0008_alter_customuser_document_type_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customuser",
            options={"verbose_name": "user", "verbose_name_plural": "users"},
        ),
    ]
