# Generated by Django 5.1.6 on 2025-03-12 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_customuser_drive_folder_id'),
        ('users', '0009_alter_customuser_options'),
    ]

    operations = [
    ]
