# Generated by Django 5.1.6 on 2025-03-17 12:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0009_userupdatelog"),
        ("users", "0010_merge_20250312_1624"),
    ]

    operations = []
