# Generated by Django 5.1.6 on 2025-03-22 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_customuser_phone'),
        ('users', 'migrate_login_history'),
    ]

    operations = [
    ]
