# Generated by Django 5.1.6 on 2025-03-21 14:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0010_alter_customuser_phone"),
        ("users", "0011_merge_0009_userupdatelog_0010_merge_20250312_1624"),
    ]

    operations = []
