# Generated by Django 5.1.6 on 2025-03-22 05:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0011_merge_20250322_0022"),
    ]

    operations = [
        migrations.DeleteModel(
            name="LoginHistory",
        ),
    ]
