# Generated by Django 5.1.6 on 2025-03-23 06:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0013_alter_userupdatelog_first_update_date_and_more"),
        ("users", "0013_merge_20250322_0919"),
    ]

    operations = []
