# Generated by Django 5.1.6 on 2025-04-07 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_userupdatelog_first_update_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': [('can_toggle_is_active', 'Puede cambiar el estado de is_active'), ('can_toggle_is_registered', 'Puede cambiar el estado de is_registered'), ('can_toggle_is_staff', 'Puede cambiar el estado de is_staff')], 'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.AlterModelOptions(
            name='documenttype',
            options={'verbose_name': 'Tipo de documento', 'verbose_name_plural': 'Tipos de documento'},
        ),
        migrations.AlterModelOptions(
            name='persontype',
            options={'verbose_name': 'Tipos de persona', 'verbose_name_plural': 'Tipos de persona'},
        ),
    ]
