# Generated by Django 5.1.6 on 2025-03-27 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_userupdatelog_first_update_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='document',
            field=models.CharField(db_index=True, max_length=15, primary_key=True, serialize=False, verbose_name='Documento'),
        ),
    ]
