# Generated by Django 5.1.6 on 2025-04-10 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_customuser_options_alter_documenttype_options_and_more'),
        ('users', '0014_merge_20250323_0143'),
    ]

    operations = [
    ]
