# Generated by Django 5.1.6 on 2025-05-29 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_customuser_options_alter_documenttype_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': [('can_toggle_is_active', 'Puede cambiar el estado de is_active'), ('can_toggle_is_registered', 'Puede cambiar el estado de is_registered'), ('can_toggle_is_staff', 'Puede cambiar el estado de is_staff'), ('can_see_incident_history', 'Puede ver el historial de incidencias')], 'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
    ]
